#!/usr/bin/env python3
import os.path
import shutil
import subprocess


PERSONAL_PUPPET = os.path.join(
    os.environ.get('XDG_CACHE_DIR', os.path.expanduser('~/.cache')),
    'personal-puppet',
)
GEM_HOME = os.path.join(PERSONAL_PUPPET, 'gems')
GEM_BIN = os.path.join(GEM_HOME, 'bin')
PUPPET_BIN = os.path.join(GEM_BIN, 'puppet')

HERE = os.path.dirname(os.path.realpath(__file__))


def _msg(s):
    print('=' * 79)
    print(s)
    print('=' * 79, flush=True)


def main(argv=None):
    os.environ['GEM_HOME'] = GEM_HOME
    os.environ['PATH'] = GEM_BIN + os.pathsep + os.environ['PATH']

    if not os.path.exists(os.path.join(GEM_BIN, 'puppet')):
        _msg('Ensuring puppet is installed...')
        subprocess.check_call((
            'gem', 'install', 'puppet', '-v', '>=5,<6', '--no-document',
        ))

    cmd = (
        'puppet', 'apply', '--modulepath', os.path.join(HERE, 'modules'),
        os.path.join(HERE, 'manifests/site.pp'),
    )
    os.execvp(shutil.which(cmd[0]), cmd)


if __name__ == '__main__':
    exit(main())
